### PR TITLE
add instance_start, instance_end, populate event_instances even when …

### PR DESCRIPTION
**Pull request by ashybaye**
Some modifications to the $data array for events to be used in templates and creating json-ld code. It will add `instance_start` and `instance_end` keys to the array, as well as populate `event_instance` correctly.

### CODE REVIEW

**Comment by richardbporter** [comment]
Looks like @adamdelaney is working on something similar: https://github.com/ITS-UofIowa/uiowa_events/compare/7.x-2.x...single-event-multiple-instances We should discuss the expectations for the single event page before proceeding.

**Comment by ashybaye** [comment]
It's similar, but it seems that it's addressing the creation of the 'instance_upcoming' variable only. It would be great to have date/time populated for any instance of the re-occurring event, not just upcoming.

**Comment by richardbporter** [comment]
I've updated this to reflect it is only ever setting the first instance. I think the removal of these variables was a breaking change of the 2.x release.

**Comment by richardbporter** [comment]
Also, thanks!

**Pull request merged**
