### PR TITLE
Add location_name variable, add location name to the teaser template

### PR DESCRIPTION
**Pull request by ashybaye**

### CODE REVIEW

**Comment by adamdelaney** [comment]
I feel like this is a bigger issue with what data we pass back to the render functions. There is a lot of data in localist, however with only pass back a small subset of data in the full_listings function. I think we should look at providing a standard way of parsing the event data and allow all render functions to have access to that data. We also tend to be parsing the  $localist_event-> data several times, which could be resolved with issue #24.

**Comment by brandonneil** [comment]
I also think we should just return back all of the data that is in localist, even though in the base module we only actually use a small subset in the templates. Then, developers on a site-by-site basis could use the data -- it would already be there.

**Comment by brandonneil** [comment]
I say we take care of the data parsing part in the subsequent issue that is breaking that into a separate function, and we commit the addition of the location name to the tpl

**Comment by brandonneil** [comment]
This is blocked on #24

**Comment by adamdelaney** [comment]
Closing this PR because this functionality has been accounted for in the 7.x-1.4 release. See uiowa_events_prepare_data(). All localist data gets returned to theming functions, for example location and can be accessed via $variables['event']['location'].

**Pull request closed without merging**
