### PR TITLE
use event_instances API

### LINKED ISSUE #106: incorrect instances printed in teaser view
Because prepare_data does not account for the start and end dates of the request. For example, any month view will show the next upcoming instance regardless of whether or not it occurs in that month.

### LINKED ISSUE #107: events that span multiple dates only listed once in week/month views
In the 1.x branch, each instance is printed with the associated date. The 2.x branch only shows one event and the next upcoming instance. This is due to the change in data structure coming from the API.

### PR DESCRIPTION
**Pull request by richardbporter**
Implements #109 

Resolves #107, resolves #106

### CODE REVIEW

**Comment by richardbporter** [comment]
This is not resolving the issues for me locally. I think because the former API did not return instances based on the start/end parameters. The 2.x version is adding _every_ instance no matter the API request. Probably requires more filtering code.

**Comment by richardbporter** [comment]
- [ ] Explicitly set a start/end parameter for each API request (tab).
- [ ] Pass the start/end parameters to uiowa_events_prepare_data().
- [ ] Only add the instance if it falls within the start/end range.
- [ ] Remove the archive filtering from uiowa_events_page_full_listing.

**Comment by joewhitsitt** [comment]
i took a stab at this. needs testing. also, i am making assumptions about the archive.

this only addresses the first three items that rick mentioned.

**Comment by joewhitsitt** [comment]
i created an alternative route https://github.com/ITS-UofIowa/uiowa_events/tree/use-default-api-display that doesn't rely on the API's month and week display_ids

i personally like this one better because it doesn't make as many assumptions.

**Comment by joewhitsitt** [comment]
the archive pager doesn't work with this

**Comment by richardbporter** [comment]
This completely hoses the pager the single event display...

**Pull request merged**
