### PR TITLE
use trimmed plain text description in teaser

### PR DESCRIPTION
**Pull request by genjohnson**
This PR is meant to address #89

### CODE REVIEW

**Comment by genjohnson** [comment]
Due to the change in template_preprocess_uiowa_events_teaser(), sites with a local version of uiowa-events-teaser.tpl.php will need to change `$variables['event']['description']` to `$variables['event']['description_text']`.

Searching for "uiowa-events-teaser.tpl.php" on GitHub returns the following sites:
- iisc.uiowa.edu
- international.uiowa.edu
- grantwood.uiowa.edu
- artshare.uiowa.edu
- law.uiowa.edu
- informatics.uiowa.edu
- hpc.uiowa.edu
- tippie.uiowa.edu
- engineering.uiowa.edu

**Comment by joewhitsitt** [comment]
Aka diff between the two and update their templates accordingly.

**Comment by joewhitsitt** [comment]
add **its.uiowa.edu** to that list

**Comment by richardbporter** [comment]
Yes, or remove it entirely if they're _only_ overriding it to print a description on the teaser.

I updated the comment and turned into a checklist.

**Comment by richardbporter** [comment]
Follow up #75

**Pull request merged**
