### PR TITLE
changed http to https

### PR DESCRIPTION
**Pull request by jzhang113**

### CODE REVIEW

**Comment by richardbporter** [comment]
@brandonneil @markahrens What should we do with this?

**Comment by brandonneil** [comment]
I don't think we can move on this until a more secure SSL cert is installed for https://events.uiowa.edu

Chrome is annoyed:
`This site uses a weak security configuration (SHA-1 signatures), so your connection may not be private.`

**Comment by genjohnson** [comment]
Just as a quick status update, we are still waiting on a more secure SSL cert for https://events.uiowa.edu.

**Comment by richardbporter** [comment]
Closing in favor of #64

**Pull request closed without merging**
