### PR TITLE
Feature/load abstraction

### LINKED ISSUE #56: Abstract uiowa_events_load arguments
Instead of defining each parameter for uiowa_events_load(), we should take an array of args. This should help with #40, as we will have to allow for multiple type params as well as additional api params for localist.

### PR DESCRIPTION
**Pull request by adamdelaney**
This PR should resolve #56, #47, #37, #26, #24, #39

### CODE REVIEW

**Comment by adamdelaney** [comment]
This PR changes uiowa_events_load function and allows the endpoint args and params to be configured. A new cache_id mechanism has been implemented as well as the parsing of parameters. Additionally all calls to uiowa_events_load() needed to be updated to reflect the new changes. Testers are welcomed to ensure that we didn't break anything here.

**Comment by adamdelaney** [comment]
There appears to be an issue with the events pager for full listing.

**Comment by adamdelaney** [comment]
Commit 811cbe1cf9e9af8199b2b9570c9cab7484fba179 should resolve #40 for pane placements. There is still some work to do to implement more flexible config such as

- Exclude
- Places
- Groups

But this commit will at least allow you to combine filters and choose the matching method.

**Comment by adamdelaney** [comment]
In uiowa_events_pane, due to a change in $form['conf'] naming conventions there is currently no backwards compatibility for the "num_of_events" as this has been replaced with "param_pp". I suggest we write an update hook and run an db_update for all uiowa_event panes and update the conf name.

**Comment by adamdelaney** [comment]
There seems to be a bug with filter past events for full-listing. I'm not quite sure what happened here since there was really no changes to how that was working. For some reason I cannot get the first IF to evaluate TRUE.

**Comment by adamdelaney** [comment]
Commit: 32ccda735439959267c8f8900131482b5792498b should resolve the filtering past events issue for full listing.

**Comment by richardbporter** [comment]
I tested this out locally and did not notice any issues.

**Pull request merged**
