### PR TITLE
Single event multiple instances

### PR DESCRIPTION
**Pull request by adamdelaney**
Updated the date instance renders.

### CODE REVIEW

**Comment by richardbporter** [comment]
Worked for me locally. I like this format.

**Comment by ashybaye** [comment]
For the single non-recurring event, in the page template, it shows "Next date: _date/time_". I don't think  "Next date:" is needed.

**Comment by adamdelaney** [comment]
@ashybaye I've added code to remove the date-instance__label if the event_instances is single valued.

**Comment by joewhitsitt** [comment]
Here is a rough search of sites using a different template or possibly a overridden preprocess for single event: https://github.com/search?q=org%3AITS-UofIowa+%22uiowa_events_single_event%22&type=Code

These sites will need to be updated so they don't break when this is pushed.

**Comment by joewhitsitt** [comment]
international.uiowa.edu has develop and master PRs to account for this.

**Comment by joewhitsitt** [comment]
engineering.uiowa.edu has a master PR to account for this.

**Comment by ashybaye** [comment]
I have a template ready to deploy as soon as the new version of the module is deployed.

**Comment by joewhitsitt** [comment]
sitenow_custom_profile engineering has a PR to account for this.

**Pull request merged**
