### PR TITLE
Config for events and event paths

### LINKED ISSUE #66: Allow configuration of events and event paths.

### PR DESCRIPTION
**Pull request by adamdelaney**
Resolves #66

### CODE REVIEW

**Comment by adamdelaney** [comment]
@brandonneil It looks like we are programmatically clearing caches in a custom submit handler, so I don't think we need this message. See uiowa_events_config_form_submit().

**Comment by brandonneil** [comment]
Ah yes!

**Comment by richardbporter** [comment]
This looks good but my use case was to _disable_ the events/* router path. That way I could register views, pages, etc. at those paths.

**Comment by richardbporter** [comment]
Actually, do we need any validation here to ensure this doesn't conflict with another router path?

Depending on your use case, it might be easier to just turn this events/* date-pager functionality off by making it a submodule.

**Comment by brandonneil** [comment]
`variable_set('uiowa_events_listing_path', 'admin');` got rid of it for you, @richardbporter

**Comment by adamdelaney** [comment]
@richardbporter I think it would be great to break some of these up into sub modules which could help with path mgmt. For example:

- uiowa_events: api calls and shared code/theming functions
  - uiowa_events_page_listing
  - uiowa_events_single_event
  - uiowa_events_pane

**Comment by joewhitsitt** [comment]
Works as expected, except do we want to sanitize these values at all? i was able to enter a special character `events!` and it worked.

**Comment by adamdelaney** [comment]
@joewhitsitt probably a good idea.

**Comment by joewhitsitt** [comment]
i won't get an award for this addition, but it does the job... i think.

**Comment by adamdelaney** [comment]
@richardbporter I don't think there is anything in core and we didn't really want a module dependency on pathauto or anything else like that.

**Comment by joewhitsitt** [comment]
@adamdelaney mentioned that the vars aren't set for existing sites. the form has default values, but i created an update hook to set them as well. also added the vars to the uninstall list

**Comment by adamdelaney** [comment]
I haven't tested this on a site, but I think this looks pretty good.

**Comment by joewhitsitt** [comment]
I created a ticket #73 to address remaining concerns about this PR.

**Pull request merged**
