### PR TITLE
Pagination

### LINKED ISSUE #4: Support pagination
For example, it seems like a month view should show all events for that month and not just the first 50.

### PR DESCRIPTION
**Pull request by richardbporter**
This resolves #4.

### CODE REVIEW

**Comment by markahrens** [comment]
Is there a reason to change the per page parameter from 50 to 25? For groups that do not want to use paging, this could be seen as a regression in functionality?

**Comment by brandonneil** [comment]
I agree with Mark, although those users never knew that they may have been missing events 51+.

In the short term, maybe we expose the pp as a parameter to uiowa_events_load(). Then we do either (or both): add configuration option for per page at admin/config/user-interface/uiowa-events or create a hook_uiowa_events_load_alter() for us to change it on a per-site basis, as well as other needs in the future.

**Comment by brandonneil** [comment]
One thing I noticed is $page is not yet documented in the uiowa_events_load() function

**Comment by richardbporter** [comment]
I was just thinking about performance. Since all the events are actually available now, less per page seemed logical.

It should be configurable but I can't get to that now. Anyway, I reverted the commit.

**Pull request merged**
